<?php
namespace Blockish\Config;

use Blockish\Traits\SingletonTrait;

defined( 'ABSPATH' ) || exit;

/**
 * Configures and initializes the Blockish Freemius integration.
 */
class Freemius {

	use SingletonTrait;

	/**
	 * Replace these placeholders with the values generated by Freemius.
	 */
	public const PRODUCT_ID = 'REPLACE_WITH_BLOCKISH_PRODUCT_ID';
	public const PUBLIC_KEY = 'pk_REPLACE_WITH_BLOCKISH_PUBLIC_KEY';

	/**
	 * Freemius SDK instance.
	 *
	 * @var \Freemius|false
	 */
	private $sdk = false;

	/**
	 * Initialize the Freemius integration.
	 */
	protected function __construct() {
		$this->sdk = $this->initialize();

		if ( $this->sdk ) {
			do_action( 'blockish/freemius/loaded', $this->sdk );
		}
	}

	/**
	 * Determine whether real Freemius credentials have been configured.
	 *
	 * @return bool
	 */
	public function is_configured() {
		return (
			(bool) preg_match( '/^[1-9][0-9]*$/', (string) self::PRODUCT_ID ) &&
			(bool) preg_match( '/^pk_[A-Za-z0-9]+$/', self::PUBLIC_KEY )
		);
	}

	/**
	 * Retrieve the initialized Freemius SDK instance.
	 *
	 * @return \Freemius|false
	 */
	public function get_sdk() {
		return $this->sdk;
	}

	/**
	 * Load and initialize the shared Freemius SDK.
	 *
	 * No Freemius menu is registered because Blockish owns its React dashboard
	 * and Addons route.
	 *
	 * @return \Freemius|false
	 */
	private function initialize() {
		if ( ! $this->is_configured() ) {
			return false;
		}

		$sdk_start = BLOCKISH_DIR . 'vendor/freemius/start.php';

		if ( ! file_exists( $sdk_start ) ) {
			return false;
		}

		require_once $sdk_start;

		if ( ! function_exists( 'fs_dynamic_init' ) ) {
			return false;
		}

		return \fs_dynamic_init(
			array(
				'id'                  => self::PRODUCT_ID,
				'slug'                => 'blockish',
				'type'                => 'plugin',
				'public_key'          => self::PUBLIC_KEY,
				'is_premium'          => false,
				'has_premium_version' => false,
				'has_paid_plans'      => false,
				'has_addons'          => true,
				'is_org_compliant'    => true,
			)
		);
	}
}
